/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PassageiroRouteImport } from './routes/passageiro'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const PassageiroRoute = PassageiroRouteImport.update({
  id: '/passageiro',
  path: '/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/motorista': typeof MotoristaRoute
  '/passageiro': typeof PassageiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/motorista': typeof MotoristaRoute
  '/passageiro': typeof PassageiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/motorista': typeof MotoristaRoute
  '/passageiro': typeof PassageiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/motorista' | '/passageiro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/motorista' | '/passageiro'
  id: '__root__' | '/' | '/auth' | '/motorista' | '/passageiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MotoristaRoute: typeof MotoristaRoute
  PassageiroRoute: typeof PassageiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passageiro': {
      id: '/passageiro'
      path: '/passageiro'
      fullPath: '/passageiro'
      preLoaderRoute: typeof PassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MotoristaRoute: MotoristaRoute,
  PassageiroRoute: PassageiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
